name: ModerationTools
version: 1.0
api-version: 1.19
author: https://github.com/enes-th/minecraft-moderations-tools
main: gg.enes.moderation.Main
commands:
  report:
    description: Report a player
    usage: /<command> <player>
  moderator:
    description: Enable moderator mode
    usage: /<command>
    permission: moderator.use.mod
  report-check:
    description: View reports of a player
    usage: /<command> <player>
    permission: moderator.use.report
  player-check:
    description: View a player's information
    usage: /<command> <player>
    permission: moderator.use.player
load: POSTWORLD