name: ModerationTools
version: 1.0
api-version: 1.19
database: true
author: https://github.com/enes-th/minecraft-moderations-tools
main: enes.plugin.moderation.Main
commands:
  report:
    description: Report a player
    usage: /report <player>
  moderator:
    description: Enable moderator mode
    usage: /moderator
    permission: moderator.use
  report-check:
    description: View reports of a player
    usage: /report-check <player>
    permission: moderator.use
    aliases:
      - rck
  player-check:
    description: View a player's information
    usage: /player-check <player>
    permission: moderator.use
    aliases:
      - pck
